-- =====================================================================
-- Serving layer — APP_REF views
-- Stable, app-facing views over the L2 ANALYTICS dynamic tables plus two
-- raw reference objects (A_PLANT, A_SUPPLY_CHAIN_NODES). This is the
-- interface the dashboard / Native App reads from.
-- =====================================================================

create or replace schema SAP_SUPPLY_CHAIN.APP_REF;

create or replace view SAP_SUPPLY_CHAIN.APP_REF.A_PLANT(
	PLANT,
	PLANT_NAME,
	FACTORY_CALENDAR,
	COUNTRY_KEY,
	CITY,
	COMPANY_CODE,
	VALUATION_AREA,
	CREATED_DATE
) as SELECT * FROM SAP_SUPPLY_CHAIN.PLANT.A_PLANT;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.A_SUPPLY_CHAIN_NODES(
	NODE_ID,
	NODE_NAME,
	NODE_TYPE,
	CITY,
	COUNTRY,
	LATITUDE,
	LONGITUDE,
	PLANT
) as SELECT * FROM SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_SUPPLY_CHAIN_NODES;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_BOM_EXPLOSION(
	PARENT_MATERIAL,
	PARENT_DESC,
	BOM_NUMBER,
	BOM_LEVEL,
	COMPONENT_MATERIAL,
	COMPONENT_DESC,
	COMPONENT_QTY,
	COMPONENT_UOM,
	BASE_QTY,
	ITEM_CATEGORY,
	COMPONENT_COST
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_BOM_EXPLOSION;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_DELIVERY_PERFORMANCE(
	DELIVERY_ID,
	SHIPPING_POINT,
	SHIPPING_POINT_DESC,
	MATERIAL,
	MATERIAL_DESC,
	DELIVERY_QTY,
	PLANNED_DELIVERY_DATE,
	ACTUAL_DELIVERY_DATE,
	ON_TIME_FLAG,
	DELAY_DAYS,
	DELIVERY_MONTH
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_DELIVERY_PERFORMANCE;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_INVENTORY_OVERVIEW(
	MATERIAL,
	MATERIAL_DESC,
	PLANT,
	PLANT_NAME,
	STORAGE_LOCATION,
	STOCK_QTY,
	STOCK_VALUE,
	DAYS_OF_INVENTORY,
	TURNOVER_RATE,
	LAST_MOVEMENT_DATE,
	OBSOLETE_FLAG
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_INVENTORY_OVERVIEW;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_MANUFACTURING_KPI(
	PLANT,
	PLANT_NAME,
	PERIOD_DATE,
	OEE_PCT,
	CYCLE_TIME_AVG,
	THROUGHPUT,
	SCRAP_RATE_PCT,
	ON_TIME_DELIVERY_PCT,
	INVENTORY_TURNOVER
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_MANUFACTURING_KPI;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_PRODUCTION_ORDER_360(
	PRODUCTION_ORDER,
	ORDER_TYPE,
	PLANT,
	PLANT_NAME,
	MATERIAL,
	MATERIAL_DESC,
	PLANNED_QTY,
	CONFIRMED_QTY,
	SCRAP_QTY,
	YIELD_QTY,
	WORK_CENTER,
	CYCLE_TIME_DAYS,
	CREATED_DATE,
	BASIC_START_DATE,
	BASIC_FINISH_DATE,
	ORDER_STATUS
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_PRODUCTION_ORDER_360;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_PROJECT_STATUS(
	PROJECT_ID,
	PROJECT_NAME,
	PLANT,
	PROJECT_STATUS,
	PLANNED_COST,
	ACTUAL_COST,
	BUDGET_VARIANCE_PCT,
	START_DATE,
	END_DATE,
	COMPLETION_PCT,
	WBS_ELEMENT,
	WBS_DESCRIPTION
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_PROJECT_STATUS;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_SUPPLIER_QUALITY(
	SUPPLIER,
	SUPPLIER_NAME,
	MATERIAL,
	MATERIAL_DESC,
	TOTAL_DELIVERED,
	DEFECT_QTY,
	DEFECT_RATE_PCT,
	ON_TIME_DELIVERY_PCT,
	QUALITY_SCORE,
	PERIOD_DATE
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_SUPPLIER_QUALITY;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_SUPPLY_CHAIN_GEO(
	FLOW_ID,
	FLOW_TYPE,
	MATERIAL_CATEGORY,
	MONTHLY_VOLUME,
	MONTHLY_VALUE,
	SOURCE_NAME,
	SOURCE_TYPE,
	SOURCE_CITY,
	SOURCE_COUNTRY,
	SOURCE_LAT,
	SOURCE_LON,
	SOURCE_PLANT,
	TARGET_NAME,
	TARGET_TYPE,
	TARGET_CITY,
	TARGET_COUNTRY,
	TARGET_LAT,
	TARGET_LON,
	TARGET_PLANT
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_SUPPLY_CHAIN_GEO;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_WORK_CENTER_UTILIZATION(
	WORK_CENTER,
	WORK_CENTER_DESC,
	PLANT,
	PLANT_NAME,
	AVAILABLE_CAPACITY_HRS,
	USED_CAPACITY_HRS,
	UTILIZATION_PCT,
	PERIOD_DATE
) as SELECT * FROM SAP_SUPPLY_CHAIN.ANALYTICS.DT_WORK_CENTER_UTILIZATION;
