-- =====================================================================
-- L2 (gold) — Analytics dynamic tables
-- Joined / enriched / aggregated analytics objects built on the raw L0
-- SAP BDC standard data products. Dynamic tables auto-refresh
-- (TARGET_LAG). Requires a warehouse named LOAD_WH (or edit WAREHOUSE).
-- =====================================================================

create or replace schema SAP_SUPPLY_CHAIN.ANALYTICS COMMENT='L2: Dynamic tables - analytics-ready joined/enriched data';

create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_BOM_EXPLOSION(
	PARENT_MATERIAL,
	PARENT_DESC,
	BOM_NUMBER,
	BOM_LEVEL,
	COMPONENT_MATERIAL,
	COMPONENT_DESC,
	COMPONENT_QTY,
	COMPONENT_UOM,
	BASE_QTY,
	ITEM_CATEGORY,
	COMPONENT_COST
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    b.PARENT_MATERIAL,
    b.PARENT_DESC,
    b.BOM_NUMBER,
    b.BOM_LEVEL,
    b.COMPONENT_MATERIAL,
    b.COMPONENT_DESC,
    b.COMPONENT_QTY,
    b.COMPONENT_UOM,
    b.BASE_QTY,
    b.ITEM_CATEGORY,
    b.COMPONENT_COST
FROM SAP_SUPPLY_CHAIN.BILL_OF_MATERIAL.A_BOM_ITEM b;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_DELIVERY_PERFORMANCE(
	DELIVERY_ID,
	SHIPPING_POINT,
	SHIPPING_POINT_DESC,
	MATERIAL,
	MATERIAL_DESC,
	DELIVERY_QTY,
	PLANNED_DELIVERY_DATE,
	ACTUAL_DELIVERY_DATE,
	ON_TIME_FLAG,
	DELAY_DAYS,
	DELIVERY_MONTH
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    d.DELIVERY_ID,
    d.SHIPPING_POINT,
    sp.SHIPPING_POINT_DESC,
    d.MATERIAL,
    d.MATERIAL_DESC,
    d.DELIVERY_QTY,
    d.PLANNED_DELIVERY_DATE,
    d.ACTUAL_DELIVERY_DATE,
    d.ON_TIME_FLAG,
    d.DELAY_DAYS,
    d.DELIVERY_MONTH
FROM SAP_SUPPLY_CHAIN.DELIVERY_MGMT_CONFIG.A_DELIVERY d
JOIN SAP_SUPPLY_CHAIN.SHIPPING_POINT.A_SHIPPING_POINT sp ON d.SHIPPING_POINT = sp.SHIPPING_POINT;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_INVENTORY_OVERVIEW(
	MATERIAL,
	MATERIAL_DESC,
	PLANT,
	PLANT_NAME,
	STORAGE_LOCATION,
	STOCK_QTY,
	STOCK_VALUE,
	DAYS_OF_INVENTORY,
	TURNOVER_RATE,
	LAST_MOVEMENT_DATE,
	OBSOLETE_FLAG
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    ms.MATERIAL,
    ms.MATERIAL_DESC,
    ms.PLANT,
    p.PLANT_NAME,
    ms.STORAGE_LOCATION,
    ms.STOCK_QTY,
    ms.STOCK_VALUE,
    ms.DAYS_OF_INVENTORY,
    ms.TURNOVER_RATE,
    ms.LAST_MOVEMENT_DATE,
    ms.OBSOLETE_FLAG
FROM SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_MATERIAL_STOCK ms
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON ms.PLANT = p.PLANT;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_MANUFACTURING_KPI(
	PLANT,
	PLANT_NAME,
	PERIOD_DATE,
	OEE_PCT,
	CYCLE_TIME_AVG,
	THROUGHPUT,
	SCRAP_RATE_PCT,
	ON_TIME_DELIVERY_PCT,
	INVENTORY_TURNOVER
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    k.PLANT,
    p.PLANT_NAME,
    k.PERIOD_DATE,
    k.OEE_PCT,
    k.CYCLE_TIME_AVG,
    k.THROUGHPUT,
    k.SCRAP_RATE_PCT,
    k.ON_TIME_DELIVERY_PCT,
    k.INVENTORY_TURNOVER
FROM SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_MANUFACTURING_KPI k
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON k.PLANT = p.PLANT;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_PRODUCTION_ORDER_360(
	PRODUCTION_ORDER,
	ORDER_TYPE,
	PLANT,
	PLANT_NAME,
	MATERIAL,
	MATERIAL_DESC,
	PLANNED_QTY,
	CONFIRMED_QTY,
	SCRAP_QTY,
	YIELD_QTY,
	WORK_CENTER,
	CYCLE_TIME_DAYS,
	CREATED_DATE,
	BASIC_START_DATE,
	BASIC_FINISH_DATE,
	ORDER_STATUS
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    po.PRODUCTION_ORDER,
    po.ORDER_TYPE,
    po.PLANT,
    p.PLANT_NAME,
    po.MATERIAL,
    po.MATERIAL_DESC,
    po.PLANNED_QTY,
    po.CONFIRMED_QTY,
    po.SCRAP_QTY,
    po.YIELD_QTY,
    po.WORK_CENTER,
    po.CYCLE_TIME_DAYS,
    po.CREATED_DATE,
    po.BASIC_START_DATE,
    po.BASIC_FINISH_DATE,
    po.ORDER_STATUS
FROM SAP_SUPPLY_CHAIN.PRODUCTION_ORDER_CONFIRM.A_PROD_ORD_CONFIRMATION po
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON po.PLANT = p.PLANT;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_PROJECT_STATUS(
	PROJECT_ID,
	PROJECT_NAME,
	PLANT,
	PROJECT_STATUS,
	PLANNED_COST,
	ACTUAL_COST,
	BUDGET_VARIANCE_PCT,
	START_DATE,
	END_DATE,
	COMPLETION_PCT,
	WBS_ELEMENT,
	WBS_DESCRIPTION
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    pj.PROJECT_ID,
    pj.PROJECT_NAME,
    pj.PLANT,
    pj.PROJECT_STATUS,
    pj.PLANNED_COST,
    pj.ACTUAL_COST,
    pj.BUDGET_VARIANCE_PCT,
    pj.START_DATE,
    pj.END_DATE,
    pj.COMPLETION_PCT,
    w.WBS_ELEMENT,
    w.WBS_DESCRIPTION
FROM SAP_SUPPLY_CHAIN.PROJECT.A_PROJECT pj
LEFT JOIN SAP_SUPPLY_CHAIN.PROJECT_NETWORK.A_PROJECT_WBS w ON pj.PROJECT_ID = w.PROJECT_ID;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_SUPPLIER_QUALITY(
	SUPPLIER,
	SUPPLIER_NAME,
	MATERIAL,
	MATERIAL_DESC,
	TOTAL_DELIVERED,
	DEFECT_QTY,
	DEFECT_RATE_PCT,
	ON_TIME_DELIVERY_PCT,
	QUALITY_SCORE,
	PERIOD_DATE
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 COMMENT='The table contains records of supplier quality metrics, specifically quality scores and delivery performance. Each record represents a supplier and includes details about the materials they provide, delivery performance, and quality metrics.'
 as
SELECT
    sq.SUPPLIER,
    sq.SUPPLIER_NAME,
    sq.MATERIAL,
    sq.MATERIAL_DESC,
    sq.TOTAL_DELIVERED,
    sq.DEFECT_QTY,
    sq.DEFECT_RATE_PCT,
    sq.ON_TIME_DELIVERY_PCT,
    sq.QUALITY_SCORE,
    sq.PERIOD_DATE
FROM SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_SUPPLIER_QUALITY sq;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_SUPPLY_CHAIN_GEO(
	FLOW_ID,
	FLOW_TYPE,
	MATERIAL_CATEGORY,
	MONTHLY_VOLUME,
	MONTHLY_VALUE,
	SOURCE_NAME,
	SOURCE_TYPE,
	SOURCE_CITY,
	SOURCE_COUNTRY,
	SOURCE_LAT,
	SOURCE_LON,
	SOURCE_PLANT,
	TARGET_NAME,
	TARGET_TYPE,
	TARGET_CITY,
	TARGET_COUNTRY,
	TARGET_LAT,
	TARGET_LON,
	TARGET_PLANT
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    f.FLOW_ID,
    f.FLOW_TYPE,
    f.MATERIAL_CATEGORY,
    f.MONTHLY_VOLUME,
    f.MONTHLY_VALUE,
    src.NODE_NAME   AS SOURCE_NAME,
    src.NODE_TYPE   AS SOURCE_TYPE,
    src.CITY        AS SOURCE_CITY,
    src.COUNTRY     AS SOURCE_COUNTRY,
    src.LATITUDE    AS SOURCE_LAT,
    src.LONGITUDE   AS SOURCE_LON,
    src.PLANT       AS SOURCE_PLANT,
    tgt.NODE_NAME   AS TARGET_NAME,
    tgt.NODE_TYPE   AS TARGET_TYPE,
    tgt.CITY        AS TARGET_CITY,
    tgt.COUNTRY     AS TARGET_COUNTRY,
    tgt.LATITUDE    AS TARGET_LAT,
    tgt.LONGITUDE   AS TARGET_LON,
    tgt.PLANT       AS TARGET_PLANT
FROM SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_SUPPLY_CHAIN_FLOWS f
JOIN SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_SUPPLY_CHAIN_NODES src ON f.SOURCE_NODE = src.NODE_ID
JOIN SAP_SUPPLY_CHAIN.MANUFACTURING_CODES.A_SUPPLY_CHAIN_NODES tgt ON f.TARGET_NODE = tgt.NODE_ID;
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_WORK_CENTER_UTILIZATION(
	WORK_CENTER,
	WORK_CENTER_DESC,
	PLANT,
	PLANT_NAME,
	AVAILABLE_CAPACITY_HRS,
	USED_CAPACITY_HRS,
	UTILIZATION_PCT,
	PERIOD_DATE
) target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
 as
SELECT
    wc.WORK_CENTER,
    w.WORK_CENTER_DESC,
    wc.PLANT,
    p.PLANT_NAME,
    wc.AVAILABLE_CAPACITY_HRS,
    wc.USED_CAPACITY_HRS,
    ROUND(100.0 * wc.USED_CAPACITY_HRS / NULLIF(wc.AVAILABLE_CAPACITY_HRS, 0), 1) AS UTILIZATION_PCT,
    wc.PERIOD_DATE
FROM SAP_SUPPLY_CHAIN.WORK_CENTER.A_WORK_CENTER_CAPACITY wc
JOIN SAP_SUPPLY_CHAIN.WORK_CENTER.A_WORK_CENTER w ON wc.WORK_CENTER = w.WORK_CENTER AND wc.PLANT = w.PLANT
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON wc.PLANT = p.PLANT;
